config/routes.rb
Gigmarklet::Application.routes.draw do

  resources :users
  get '/users/:id/events' => 'users#events'

  resources :events

  post '/add_url' => 'home#add_url'
  get '/gigmarklet' => 'events#create'

  get '/register' => 'register#new'
  post '/register' => 'register#create'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

  root :to => 'home#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  password_digest :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :events
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  before_filter :ensure_logged_in

  def index
    @users = User.all
  end

  def show
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = @auth
    end
  end

  # def events
  #   @events = Events.where(:user_id => params[:id])
  # end

  def edit
    if params[:id]
      @profile = User.find(params[:id])
    else
      @profile = @auth
    end
  end

  def update
    if @auth.update_attributes(params[:user])
      redirect_to profile_path
    else
      render :edit
    end
  end

  private
  def ensure_logged_in
    redirect_to root_path if @auth.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :ensure_logged_in

  def index
    @users = User.all
  end

  def show
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = @auth
    end
  end

  def events
    @events = @auth.events
  end

  def edit
    if params[:id]
      @profile = User.find(params[:id])
    else
      @profile = @auth
    end
  end

  def update
    if @auth.update_attributes(params[:user])
      redirect_to profile_path
    else
      render :edit
    end
  end

  private
  def ensure_logged_in
    redirect_to root_path if @auth.nil?
  end
end

app/views/users/events.html.erb
<div class="event">
  <%= @events.each do |event| %>
    <div class="link"> <h3> <%= link_to "event link", event.link %> </h3> </div>
    <div class="artist"> <h4> <%= event.artist %> </h4> </div>
    <div class="date"><%= event.event_date %></div>
    <div class="venue"><%= event.venue %></div>
    <div class="location"><%= event.location %></div>
    <div class='links'>
        <%= link_to 'Edit', edit_event_path(event) %>
        <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>

</div>

app/views/users/index.html.erb
<h2>Users index page</h2>

app/views/users/show.html.erb
<h2>User show page</h2>